<script src="<?= base_url('assets/profile/js/jquery-3.4.1.min.js'); ?>"></script>
<script src="<?= base_url('assets/profile/js/popper.min.js'); ?>"></script>
<script src="<?= base_url('assets/profile/js/bootstrap.min.js'); ?>"></script>
<script src="<?= base_url('assets/profile/js/owl.carousel.min.js'); ?>"></script>
<script src="<?= base_url('assets/profile/js/jquery.animateNumber.min.js'); ?>"></script>
<script src="<?= base_url('assets/profile/js/jquery.waypoints.min.js'); ?>"></script>
<script src="<?= base_url('assets/profile/js/jquery.fancybox.min.js'); ?>"></script>
<script src="<?= base_url('assets/profile/js/jquery.sticky.js'); ?>"></script>
<script src="<?= base_url('assets/profile/js/aos.js'); ?>"></script>
<script src="<?= base_url('assets/profile/js/custom.js'); ?>"></script>